// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919180205_FIX19SET25")]
    partial class FIX19SET25
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Medalha", b =>
                {
                    b.Property<int>("IdMedalha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedalha"));

                    b.Property<DateTime?>("DataCassacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NBolCassacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NBolConcessao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMedalha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Re")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoMedalha")
                        .HasColumnType("int");

                    b.HasKey("IdMedalha");

                    b.HasIndex("Re");

                    b.ToTable("Tbl_Medalhas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Opm", b =>
                {
                    b.Property<string>("CodOpm")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPmPai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodOpm");

                    b.ToTable("Tbl_Opm", (string)null);

                    b.HasData(
                        new
                        {
                            CodOpm = "607070000",
                            Descricao = "7.bpm/i",
                            OPmPai = "607000000"
                        },
                        new
                        {
                            CodOpm = "607500000",
                            Descricao = "50.bpm/i",
                            OPmPai = "607000000"
                        },
                        new
                        {
                            CodOpm = "607400000",
                            Descricao = "40.bpm/i",
                            OPmPai = "607000000"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Policial", b =>
                {
                    b.Property<string>("Re")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodOpm")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostoGrad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Re");

                    b.HasIndex("CodOpm");

                    b.ToTable("Tbl_Policial", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Medalha", b =>
                {
                    b.HasOne("Domain.Entities.Policial", "Policial")
                        .WithMany("medalhas")
                        .HasForeignKey("Re")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policial");
                });

            modelBuilder.Entity("Domain.Entities.Policial", b =>
                {
                    b.HasOne("Domain.Entities.Opm", "Opm")
                        .WithMany()
                        .HasForeignKey("CodOpm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opm");
                });

            modelBuilder.Entity("Domain.Entities.Policial", b =>
                {
                    b.Navigation("medalhas");
                });
#pragma warning restore 612, 618
        }
    }
}
